import { DataSource, FindOptionsRelations, FindOptionsOrder } from 'typeorm';
import { Patient as DomainPatient } from '../../domain/entities/Patient';
import { Patient as TypeOrmPatient } from '../../infrastructure/database/entities/Patient';
import { Name } from '../../domain/value-objects/Name';
import { DateOfBirth } from '../../domain/value-objects/DateOfBirth';
import { DatabaseError } from '../../infrastructure/errors/InfrastructureError';
import { PatientMapper } from '../../infrastructure/database/mappers/PatientMapper';

export class PatientService {
  constructor(private readonly dataSource: DataSource) {}

  async getAllPatients(): Promise<DomainPatient[]> {
    try {
      const patientRepository = this.dataSource.getRepository(TypeOrmPatient);
      const typeOrmPatients = await patientRepository.find({
        order: { createdAt: 'DESC' } as FindOptionsOrder<TypeOrmPatient>,
      });
      return typeOrmPatients.map(PatientMapper.toDomain);
    } catch (error) {
      throw new DatabaseError('Failed to fetch patients');
    }
  }

  async getPatientById(id: string): Promise<DomainPatient | null> {
    try {
      const patientRepository = this.dataSource.getRepository(TypeOrmPatient);
      const typeOrmPatient = await patientRepository.findOne({
        where: { id },
        relations: {
          notes: {
            audioFile: true,
          },
        } as FindOptionsRelations<TypeOrmPatient>,
        order: {
          notes: {
            createdAt: 'DESC',
          },
        } as FindOptionsOrder<TypeOrmPatient>,
      });

      return typeOrmPatient ? PatientMapper.toDomain(typeOrmPatient) : null;
    } catch (error) {
      throw new DatabaseError('Failed to fetch patient');
    }
  }

  async createPatient(data: { name: string; dob: Date }): Promise<DomainPatient> {
    try {
      const patientRepository = this.dataSource.getRepository(TypeOrmPatient);
      const name = new Name(data.name);
      const dateOfBirth = new DateOfBirth(data.dob);
      
      const domainPatient = new DomainPatient(
        '', // ID will be generated by TypeORM
        name,
        dateOfBirth
      );
      
      const typeOrmPatient = PatientMapper.toTypeOrm(domainPatient);
      const savedPatient = await patientRepository.save(typeOrmPatient);
      
      return PatientMapper.toDomain(savedPatient);
    } catch (error) {
      throw new DatabaseError('Failed to create patient');
    }
  }

  async updatePatient(
    id: string,
    data: Partial<{ name: string; dob: Date }>
  ): Promise<DomainPatient | null> {
    try {
      const patientRepository = this.dataSource.getRepository(TypeOrmPatient);
      const typeOrmPatient = await patientRepository.findOne({ where: { id } });
      
      if (!typeOrmPatient) {
        return null;
      }

      const domainPatient = PatientMapper.toDomain(typeOrmPatient);

      if (data.name) {
        domainPatient.updateDetails(new Name(data.name), domainPatient.getDob());
      }
      
      if (data.dob) {
        domainPatient.updateDetails(domainPatient.getName(), new DateOfBirth(data.dob));
      }

      const updatedTypeOrmPatient = PatientMapper.toTypeOrm(domainPatient);
      const savedPatient = await patientRepository.save(updatedTypeOrmPatient);
      
      return PatientMapper.toDomain(savedPatient);
    } catch (error) {
      throw new DatabaseError('Failed to update patient');
    }
  }

  async deletePatient(id: string): Promise<boolean> {
    try {
      const patientRepository = this.dataSource.getRepository(TypeOrmPatient);
      const result = await patientRepository.delete(id);
      return result.affected ? result.affected > 0 : false;
    } catch (error) {
      throw new DatabaseError('Failed to delete patient');
    }
  }
} 